src/Entity/Author.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Author.
 *
 * @ORM\Table(name="author")
 * @ORM\Entity
 */
class Author
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="lastname", type="string", length=255, unique=true)
     */
    private $lastname;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="firstname", type="string", length=255, unique=true)
     */
    private $firstname;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="short_bio", type="string", length=500)
     */
    private $shortBio;

    /**
     * @var string
     * @Assert\NotBlank
     * @Assert\Length(min=10, max=20, minMessage="min_length", maxMessage="max_length")
     * @Assert\Regex(pattern="/^(0|\+33)[1-9]([-. ]?[0-9]{2}){4}$/")
     * @ORM\Column(name="phone", type="string", length=10, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=60, unique=true)
     * @Assert\NotBlank
     * @Assert\Length(max=60)
     * @Assert\Email
     */
    private $email;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="company", type="string", length=255)
     */
    private $company;

    /**
     * @var string
     * @ORM\Column(name="facebook", type="string", length=255, nullable=true)
     */
    private $facebook;

    /**
     * @var string
     * @ORM\Column(name="twitter", type="string", length=255, nullable=true)
     */
    private $twitter;

    /**
     * @var string
     * @ORM\Column(name="github", type="string", length=255, nullable=true)
     */
    private $github;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set lastname.
     *
     * @param string $lastname
     *
     * @return Author
     */
    public function setLastName($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getLastName()
    {
        return $this->lastname;
    }

    /**
     * Set title.
     *
     * @param string $title
     *
     * @return Author
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Get firstname.
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set $firstname.
     *
     * @param string $firstname
     *
     * @return Author
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set email.
     *
     * @param string $email
     *
     * @return Author
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * Set company.
     *
     * @param string $company
     *
     * @return Author
     */
    public function setCompany($company)
    {
        $this->company = $company;

        return $this;
    }

    /**
     * Get company.
     *
     * @return string
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Set shortBio.
     *
     * @param string $shortBio
     *
     * @return Author
     */
    public function setShortBio($shortBio)
    {
        $this->shortBio = $shortBio;

        return $this;
    }

    /**
     * Get shortBio.
     *
     * @return string
     */
    public function getShortBio()
    {
        return $this->shortBio;
    }

    /**
     * Set phone.
     *
     * @param string $phone
     *
     * @return Author
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone.
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set facebook.
     *
     * @param string $facebook
     *
     * @return Author
     */
    public function setFacebook($facebook)
    {
        $this->facebook = $facebook;

        return $this;
    }

    /**
     * Get facebook.
     *
     * @return string
     */
    public function getFacebook()
    {
        return $this->facebook;
    }

    /**
     * Set twitter.
     *
     * @param string $twitter
     *
     * @return Author
     */
    public function setTwitter($twitter)
    {
        $this->twitter = $twitter;

        return $this;
    }

    /**
     * Get twitter.
     *
     * @return string
     */
    public function getTwitter()
    {
        return $this->twitter;
    }

    /**
     * Set github.
     *
     * @param string $github
     *
     * @return Author
     */
    public function setGithub($github)
    {
        $this->github = $github;

        return $this;
    }

    /**
     * Get github.
     *
     * @return string
     */
    public function getGithub()
    {
        return $this->github;
    }
}

src/Controller/BlogController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Author;
use App\Repository\AuthorRepository;
use App\Repository\BlogPostRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    /** @var int */
    const POST_LIMIT = 5;

    /**
     * @var AuthorRepository
     */
    private $authorRepository;

    /**
     * @var BlogPostRepository
     */
    private $blogPostRepository;

    public function __construct(RegistryInterface $registry, BlogPostRepository $blogPostRepository, AuthorRepository $authorRepository)
    {
        $this->blogPostRepository = $blogPostRepository;
        $this->authorRepository = $authorRepository;
    }

    /**
     * @Route("/", name="homepage")
     * @Route("/entries", name="entries")
     */
    public function entriesAction(Request $request)
    {
        $page = 1;
        if ($request->get('page')) {
            $page = $request->get('page');
        }

        return $this->render('blog/entries.html.twig', [
            'blogPosts' => $this->blogPostRepository->getAllPosts($page, self::POST_LIMIT),
            'totalBlogPosts' => $this->blogPostRepository->getPostCount(),
            'page' => $page,
            'entryLimit' => self::POST_LIMIT,
        ]);
    }

    /**
     * @Route("/entry/{slug}", name="entry")
     */
    public function entryAction(String $slug)
    {
        $blogPost = $this->blogPostRepository->findOneBySlug($slug);
        if (!$blogPost) {
            $this->addFlash('error', 'Unable to find entry!');

            return $this->redirectToRoute('entries');
        }

        return $this->render('blog/entry.html.twig', [
            'blogPost' => $blogPost,
        ]);
    }

    /**
     * @Route("/author/{authorId}", name="author")
     */
    public function authorAction($authorId)
    {
        $author = $this->authorRepository->findOneById($authorId);

        if (!$author) {
            $this->addFlash('error', 'Unable to find author!');

            return $this->redirectToRoute('entries');
        }

        return $this->render('blog/author.html.twig', [
            'author' => $author,
        ]);
    }
}

templates/blog/article.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    {% block title %}Article{% endblock %}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="blog-header">
            <h1 class="blog-title">Blog</h1>
            <p class="lead blog-description">Description</p>
        </div>

        <div class="row">
            <div class="col-sm-8 blog-main">
                <div class="blog-post">
                    <h2 class="blog-post-title">{{ blogPost.title }}</h2>
                    <p class="blog-post-meta">
                        {{ blogPost.updatedAt|date('F j, Y') }} by
                        {% dump(blogPost.author) %}
                        {% if blogPost.author == null %}
                            Author Unknow
                        {% else %}
                            <a href="{{ path('author', {'authorId': blogPost.author.id}) }}">
                                {{ blogPost.author.lastname }}
                            </a>
                        {% endif %}
                    </p>
                    <h3>Description:</h3>
                    <p>{{ blogPost.description|raw }}</p>

                    <h3>Body:</h3>
                    <p>{{ blogPost.body|raw }}</p>
                    <img src="{{ asset('uploads/img/' ~ blogPost.imgUploaded) }}" alt="{{ blogPost.imgUploaded }}">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/author.html.twig
{% extends 'base.html.twig' %}
{% block title %}Author{% endblock %}

{% block body %}
    <div class="container">
        <div class="blog-header">
            <h1 class="blog-title">Author</h1>
            <p class="lead blog-description">Author</p>
        </div>

        <div class="row">
            <div class="col-sm-8 blog-main">
                <div class="blog-post">
                    <h2 class="blog-post-title">{{ author.lastName }}</h2>

                    <p>Title: {{ author.title }}</p>
                    <p>Company: {{ author.company }}</p>
                    <p>Short Biography: {{ author.shortBio }}</p>
                    <ul>
                        {% if author.getPhone %}
                            <li>{{ author.phone }}</li>
                        {% endif %}
                        {% if author.getFacebook %}
                            <li>{{ author.facebook }}</li>
                        {% endif %}
                        {% if author.getTwitter %}
                            <li>{{ author.twitter }}</li>
                        {% endif %}
                        {% if author.getGithub %}
                            <li>{{ author.github }}</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/entries.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="container">
        <div class="blog-header">
            <h1 class="blog-title">Blog tutorial</h1>
        </div>

        <div class="row">
            <div class="col-sm-8 blog-main">
                {% for blogPost in blogPosts %}
                    {% set paragraphs = blogPost.description|split('</p>') %}
                    {% set firstParagraph = paragraphs|first ~ '</p>' %}
                    <div class="blog-post">
                        <h2 class="blog-post-title">
                            <a href="{{ path('entry', {'slug': blogPost.slug}) }}">
                                {{ blogPost.title }}
                            </a>
                        </h2>
                        <p class="blog-post-meta">
                            {{ blogPost.getUpdatedAt|date('F j, Y') }} by

                            {% if blogPost.author %}
                                <a href="{{ path('author', {'authorId': blogPost.author.id }) }}">
                                    {{ blogPost.author.lastname }}
                                </a>
                            {% else %}
                                Unknown Author
                            {% endif %}
                        </p>
                        {{ firstParagraph|raw }}<br/>
                        <a href="{{ path('entry', {'slug': blogPost.slug}) }}">Read More</a>
                    </div>
                {% else %}
                    <div class="alert alert-danger" role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                        <span class="sr-only">Error:</span>
                        You have no blog articles. Please log in and create an article.
                    </div>
                {% endfor %}

                {% set canPrevious = page > 1 %}
                {% set canNext = (page * entryLimit) < totalBlogPosts %}
                <nav>
                    <ul class="pager">
                        <li class="previous {% if canPrevious == false %}disabled{% endif %}">
                            <a href="{% if canPrevious %}{{ path('entries', {'page': page - 1}) }}{% endif %}">
                                <span aria-hidden="true">&larr;</span> Older
                            </a>
                        </li>
                        <li class="next {% if canNext == false %}disabled{% endif %}">
                            <a href="{% if canNext %}{{ path('entries', {'page': page + 1}) }}{% endif %}">
                                Newer <span aria-hidden="true">&rarr;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/entry.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    {% block title %}Entry{% endblock %}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="blog-header">
            <h1 class="blog-title">Blog</h1>
            <p class="lead blog-description">Description Test</p>
        </div>

        <div class="row">
            <div class="col-sm-8 blog-main">
                <div class="blog-post">
                    <h2 class="blog-post-title">{{ blogPost.title }}</h2>
                    <p class="blog-post-meta">
                        {{ blogPost.updatedAt|date('F j, Y') }} by
                        {% dump(blogPost.author) %}
                        {% if blogPost.author == null %}
                            Author Unknow
                        {% else %}
                            <a href="{{ path('author', {'authorId': blogPost.author.id}) }}">
                                {{ blogPost.author.lastname }}
                            </a>
                        {% endif %}
                    </p>
                    <h3>Description:</h3>
                    <p>{{ blogPost.description|raw }}</p>

                    <h3>Body:</h3>
                    <p>{{ blogPost.body|raw }}</p>
                    <img src="{{ asset('uploads/img/' ~ blogPost.imgUploaded) }}" alt="{{ blogPost.imgUploaded }}">
                </div>
            </div>
        </div>
    </div>
{% endblock %}